version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "1001:80"
    volumes:
      - .:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8181:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - php
