version: '3.8'

services:
  php:
    build: .
    ports:
      - "1001:80"
    volumes:
      - .:/var/www/html
    networks:
      - php_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    networks:
      - php_network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    networks:
      - php_network
